### ISSUE TITLE
Dateien löschen 

### ISSUE THREAD

**Issue by Revuexz** [maxsrl/moeshare#3]
Wie kann ich Dateien löschen? Die Delete URL geht nicht.
Ist ein Dashboard geplant mit einer Liste aller Bilder? 

Wäre es möglich das wenn man Zip Dateien oder so hochlädt, dort auch ein Zip logo ist im Discord embed?

**Comment by MaximilianGT500** [comment]
Du musst eine DELETE-Request an /file senden. Dies geht z.B. einfach mit der Browsererweiterung: RestMan.

Nein, ein Dashboard ist derzeit nicht geplant. 

Das könnte ich auf die ToDo fürs nächste Update setzen.
