### ISSUE TITLE
failed to install npm packages

### ISSUE THREAD

**Issue by Hunter-Matata** [maxsrl/moeshare#8]
Grüße,
ich bekomme nach dem Package Install den Error das mehrere Packages depricated sind. Den Server selbst kann ich starten, wenn ich aber auf die Seite gehen will, bekomme ich die Apache Index Seite. Vermute mal das es an den Packages liegt, weiß aber keine genauere Lösung da jetzt?

Bilder: https://imgur.com/a/fVU35JB

**Comment by MaximilianGT500** [comment]
Hallo,

ich sehe keine Fehler. Das ist ein NodeJS Anwendung. Die muss nicht ins Web-Verzeichnis. Installiere es am besten im /home Verzeichnis. Der Standart Port lautet 3000.

**Comment by Hunter-Matata** [comment]
Moin,

Hatte deine Antwort jetzt erst durch Zufall gesehen. Die Seite läuft im Docker, aber redirected immer um. Habe alles versucht von 0.0.0.0 bis hin zur richtigen IP der Seite, aber habe bis jetzt noch nicht einmal die Seite gesehen. Evtl übersehe ich da was, aber weiß nicht genau was da in den Redirect in der .env und der docker-compose.yml rein soll oder ob man das irgendwie weglassen kann.

Grüße.

**Comment by MaximilianGT500** [comment]
Hallo,

Du musst zwei Sachen angeben: BASE_URL und REDIRECT_URL. Leider kann ich wenig mit den Informationen anfangen, da ich nicht weiß, was du mit weiterleiten meinst. Wohin wirst du Weitergeleitet und was versuchst du aufzurufen?

MfG
Maximilian Stumpf

**Comment by Hunter-Matata** [comment]
Ich meine die:

- REDIRECT_URL=https://example.com # Wohin soll man Weitergeleitet werden, wenn man / aufruft?

Was muss da genau rein? Und muss die Base URL auf die IP des Servers gelenkt werden?

**Comment by MaximilianGT500** [comment]
Hallo,

dort muss eine beliebige Seite hinein, wohin man geleitet werden soll, wenn man BASE_URL/ aufruft, da es keine Homepage gibt.

BASE_URL ist am Ende die Domain, welche du dann den Leuten sendest auf z.B. Discord. Du musst also mit ein Reverse Proxy eine Domain auf Port 3000 leiten.

**Comment by Hunter-Matata** [comment]
Ahhhh okay, und wie kommt man dann speziell auf die Login Seite?

**Comment by MaximilianGT500** [comment]
Hallo,

USE_DASHBOARD machst du auf "true" und dann gehst du zu BASE_URL/dashboard

**Comment by Hunter-Matata** [comment]
Ah jetzt funktioniert es danke!
